baseurl = "https://e10ulen.github.io"
title = "依藤"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "rokkaku"

[taxonomies]
  tag = "tags"
  archive = "archives"

[params]
  limitNumberOfLatests = 10
  logoHtml = ""
  styles = ["/css/tags.css"]
  github = "e10ulen"
  twitter = "e10ulen"
  copyrightHtml = "Copyright &copy; e10ulen 2018"

  [params.fontAwesome]
  #  embedCode = "xxxx"

  [params.highlightjs]
  #  url = "/js/highlight.pack.js"

  [params.ga]
  #  trackingId = "xxxx"
