baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "ja"
title                   = "幽玄怪社 依藤幸夢店"
theme                   = "robust"

googleAnalytics = "UA-XXXXXXXX-XX" # Optional
disqusShortname = "e10ulensite"

[params]
  description = "This is site description"
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/author.png"
  name = "依藤(えとう)"
  description = "<a href='/about/'>About</a>:こちらをご覧ください<br><a href='/link'>Link</a><br /><a href='/ohw/'>OneHourWrite</a>:ワンライについて記載しています。<br /><a href='/photo'>Photo</a>:頂きものや、キャラクターの設定資料です。"
  facebook = ""
  twitter = "https://twitter.com/e10ulen"
  github = "https://github.com/e10ulen"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.