baseURL = "https://e10ulen.github.io"
languageCode = "ja-JP"
title = "scattered pieces of paper"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

theme = "Memorandum"    #Required
hasCJKLanguage = true

copyright = "&copy; 2021 <a href=\"https://e10ulen.github.io/\" target=\"_blank\">e10ulen</a>"
disqusShortname = ""
summarylength = 200

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "全て雑記、責任なんて何処かに置いてきた。"
  keywords = []
  author = "e10ulen"
  profile = "散らかった紙に埋もれる <a href=\"https://e10ulen.github.io/\" target=\"_blank\">e10ulen</a>"
  displayauthor = false
  DateForm = "2006-01-02"
  sharingicons = true

[params.highlight]
theme = "monokai-sublime"

[[params.social]]
url = "https://github.com/e10ulen"
fa_icon_class = "fab fa-github"

[[params.social]]
url = "https://twitter.com/e10ulen"
fa_icon_class = "fab fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon_class = "fas fa-rss"