theme           = "hugo-theme-text"
baseurl         = "http://slcb.xyz"
title           = "幽玄怪社 依藤工夢店"
languageCode    = "ja" #ISO639/RFC4646 #optional
disqusShortname = "e10ulensite" #optional

[author]
  name      = "依藤"
  url       = "/about/" #optional
  avatar    = "/images/avatar.jpg" #optional
  license   = "CC-License: by-nc-nd" #optional
  github    = "e10ulen" #optional
  twitter   = "e10ulen" #optional
  medium    = "" #optional
  tumblr    = "" #optional
  instagram = "" #optional
  flickr    = "" #optional
  facebook  = "" #optional
  linkedin  = "" #optional
  flattr    = "" #optional

[params]
since       = "2017-01-01" #datetime format #optional
description = "個人サークル ゆうげんがいしゃ　えとうこうむてん" #optional
favicon     = "/favicon.ico" #optional
