baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "ja"
title                   = "幽玄怪社 依藤幸夢店"
theme                   = "sam"
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/favicon.ico"
    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
    pygmentsCodefences  = true
    homepage            = "."                        # What to call the home page link
    galleryFolder       = ""                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "依藤幸夢店"

# Metadata
    description         = "個人サークル 依藤幸夢店"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = ""                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/blog"
    text = "writing & create"

[[params.mainMenu]]
    link = "/about"
    text = "who is slcb?"

[[params.mainMenu]]
    link = "/link"
    text = "site..."

[[params.mainMenu]]
    link = "/link"
    text = "photo..."

[[params.mainMenu]]
    link = "/ohw"
    text = "one hour write"
