baseURL = "https://e10ulen.github.io/"
languageCode = "ja-JP"
title = "雑記ログ"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "e10ulen"
  description = "Stand Alone Complex."
  github = "e10ulen"
# facebook = "e10ulen"
  twitter = "e10ulen"
# linkedin = "e10ulen"
  instagram = "e10ulen"
# tumblr = "e10ulen"
# email = "e10ulen@gmail.com"
  url = "https://e10ulen.github.io"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  userIcon = "images/avatar.png"
  favicon = "/images/github.png"
  location = "Tokyo, Japan."

# [[params.links]]
#   title = "Link"
#   href = "https://github.github.io/e10ulen"
# [[params.links]]
#   title = "Link2"
#   href = "https://e10ulen.github.io"
#   icon = "https://e10ulen.github.io/images/profile.jpg"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
